export const PATHS = {
  login: '/login',
  dashboard: '/',
  admissions: '/admissions',
  students: '/students',
  parents: '/parents',
  teachers: '/teachers',
  programs: '/programs',
  classes: '/classes',
  classrooms: '/classrooms',
  schedules: '/schedules',
  tuition: '/tuition',
  payments: '/payments',
  attendance: '/attendance',
  examinations: '/examinations',
  notifications: '/notifications',
  reports: '/reports',
  users: '/users',
  roles: '/roles',
  auditLogs: '/audit-logs',
}
export const NAV_ITEMS = [
  { label: 'Tổng quan', path: PATHS.dashboard, roles: ['*'] },
  { label: 'Tuyển sinh', path: PATHS.admissions, roles: ['*'] },
  { label: 'Học viên', path: PATHS.students, roles: ['*'] },
  { label: 'Phụ huynh', path: PATHS.parents, roles: ['*'] },
  { label: 'Giáo viên', path: PATHS.teachers, roles: ['*'] },
  { label: 'Chương trình', path: PATHS.programs, roles: ['*'] },
  { label: 'Lớp học', path: PATHS.classes, roles: ['*'] },
  { label: 'Phòng học', path: PATHS.classrooms, roles: ['*'] },
  { label: 'Lịch học', path: PATHS.schedules, roles: ['*'] },
  { label: 'Học phí', path: PATHS.tuition, roles: ['*'] },
  { label: 'Thanh toán', path: PATHS.payments, roles: ['*'] },
  { label: 'Điểm danh', path: PATHS.attendance, roles: ['*'] },
  { label: 'Kiểm tra', path: PATHS.examinations, roles: ['*'] },
  { label: 'Thông báo', path: PATHS.notifications, roles: ['*'] },
  { label: 'Báo cáo', path: PATHS.reports, roles: ['*'] },
  { label: 'Người dùng', path: PATHS.users, roles: ['admin'] },
  { label: 'Vai trò', path: PATHS.roles, roles: ['admin'] },
  { label: 'Nhật ký', path: PATHS.auditLogs, roles: ['admin'] },
]

